version: '3'
services:
  bot:
    container_name: 'HamsterKombatBot'
    build: .
    stop_signal: SIGINT
    restart: unless-stopped
    command: 
      - python3
      - main.py
      - -a
<<<<<<< HEAD
      - "${ARGUMENT}"
=======
      - '2'
>>>>>>> refs/remotes/origin/main
    volumes:
      - ./sessions:/app/sessions
      - ./proxies.txt:/app/proxies.txt
    env_file:
      - .env
